I have a bunch of personal files that have timestamps in their
names. For example,

#+begin_src text
20190615-070543.jpeg
20190615-070543 20190615-070544.jpeg
20190615-070545---receipt.jpeg
#+end_src

I want to cite them in my org files with ease, thus coming up
with this little program. It adds a [[https://orgmode.org/manual/Adding-Hyperlink-Types.html#Adding-Hyperlink-Types][customized org link type]]
=tsl=.

* Example

The following org link of customized type (=tsl=) should bring
you to all files under TSL:LIB that have the string
=20190610-******= in name, and also pass

From the org link:
#+begin_src org
[[tsl:20190610::(:name ("memory" "family") :hash "^304e")]]
#+end_src

this program will collect each file in one of the directory
under =tsl:lib=, if the followings are true.

1. That file has the string =20190610-******= in its name.

2. That file passes the name test and hash test: its absolute
   path, as a string, must matches the regex query =memory= and
   =family=; its md5sum, as a string, must matches the regex query
   =^304e=.

Variants are allowed. For example

#+begin_src org
[[tsl:2019::(:name "family")]]
[[tsl:201906::(:hash "^304e")]]
[[tsl:20190610-1543::(:name ("memory" "family"))]]
[[tsl:20190610-154317]]
#+end_src

Note that if the =:hash= slot is nil, no hash computations will
be performed. This enhances the speed a lot. So only use it
when it's necessary.
